package com.azaatar.eventguard.domain;

public enum RejectionStatus {
    NONE,
    DUPLICATE_PAYMENT_ID,
    NON_POSITIVE_AMOUNT, // Parser
    UNSUPPORTED_CURRENCY,
    INVALID_PAYMENT_STATUS,
    MISSING_PAYMENT_ID,
    MISSING_ACCOUNT_ID,
    MISSING_CUSTOMER_NAME,
    MISSING_CUSTOMER_EMAIL,
    MISSING_AMOUNT,
    MISSING_CURRENCY,
    MISSING_STATUS
}
